# Generated by Django 6.0.5 on 2026-06-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningJobGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Commercial Office, Kitchen Deep Clean', max_length=150)),
                ('image', models.ImageField(help_text='Upload the job photo here', upload_to='cleaning_gallery/')),
                ('alt_text', models.CharField(blank=True, help_text='Description for search engines and screen readers', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cleaning Gallery Image',
                'verbose_name_plural': 'Cleaning Gallery Images',
                'ordering': ['-created_at'],
            },
        ),
    ]
